=== petrochenko-pavel-a/raml-spec/labs/geonames/schemas/get-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "alternateNames" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "lang" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "countryName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "adminCode1" : {
      "type" : "string" ,
      "required" : false
    } ,
    "lng" : {
      "type" : "string" ,
      "required" : false
    } ,
    "adminName2" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fcodeName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "adminName3" : {
      "type" : "string" ,
      "required" : false
    } ,
    "timezone" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "dstOffset" : {
          "type" : "number" ,
          "required" : false
        } ,
        "gmtOffset" : {
          "type" : "number" ,
          "required" : false
        } ,
        "timeZoneId" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "adminName4" : {
      "type" : "string" ,
      "required" : false
    } ,
    "adminName5" : {
      "type" : "string" ,
      "required" : false
    } ,
    "bbox" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "south" : {
          "type" : "number" ,
          "required" : false
        } ,
        "east" : {
          "type" : "number" ,
          "required" : false
        } ,
        "north" : {
          "type" : "number" ,
          "required" : false
        } ,
        "west" : {
          "type" : "number" ,
          "required" : false
        }
      }
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fcode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "geonameId" : {
      "type" : "number" ,
      "required" : false
    } ,
    "lat" : {
      "type" : "string" ,
      "required" : false
    } ,
    "population" : {
      "type" : "number" ,
      "required" : false
    } ,
    "adminName1" : {
      "type" : "string" ,
      "required" : false
    } ,
    "countryId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "adminId1" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fclName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "countryCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "srtm3" : {
      "type" : "number" ,
      "required" : false
    } ,
    "toponymName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fcl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "continentCode" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== petrochenko-pavel-a/raml-spec/labs/geonames/examples/get-example.json
{
  "alternateNames" : [
    {
      "name" : "K큰h-e Zardar" ,
      "lang" : "fa"
    }
  ] ,
  "countryName" : "Iran" ,
  "adminCode1" : "23" ,
  "lng" : "49.13333" ,
  "adminName2" : "" ,
  "fcodeName" : "mountain" ,
  "adminName3" : "" ,
  "timezone" : {
    "dstOffset" : 4.5 ,
    "gmtOffset" : 3.5 ,
    "timeZoneId" : "Asia/Tehran"
  } ,
  "adminName4" : "" ,
  "adminName5" : "" ,
  "bbox" : {
    "south" : 42.38232782540232 ,
    "east" : 21.740092679772783 ,
    "north" : 42.391321474154076 ,
    "west" : 21.727915361609018
  } ,
  "name" : "K큰h-e Zardar" ,
  "fcode" : "MT" ,
  "geonameId" : 1 ,
  "lat" : "32.98333" ,
  "population" : 0 ,
  "adminName1" : "Lorest훮n" ,
  "countryId" : "130758" ,
  "adminId1" : "125605" ,
  "fclName" : "mountain,hill,rock,... " ,
  "countryCode" : "IR" ,
  "srtm3" : 1473 ,
  "toponymName" : "K큰h-e Zardar" ,
  "fcl" : "T" ,
  "continentCode" : "AS"
}
